name: "Batpred"
description: "Batpred add-on"
version: "1.0.9"
slug: "batpred"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
uart: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
startup: services
ports:
  8000/tcp: 8000
