name: "Batpred"
description: "Batpred add-on"
version: "1.0.18"
slug: "batpred"
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - "mqtt:want"
homeassistant_api: true
uart: true
boot:  auto
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
startup: services
host_network: true
options:
  MQTT_OUTPUT: True
  MQTT_ADDRESS: "core-mosquitto"
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  MQTT_TOPIC: ""
  MQTT_PORT: 1883
  MQTT_RETAIN: False
  HOSTIP: "homeassistant.local"
schema: 
  MQTT_OUTPUT: bool
  MQTT_ADDRESS: str
  MQTT_USERNAME: "str?"
  MQTT_PASSWORD: "str?"
  MQTT_TOPIC: "str?"
  MQTT_PORT: int
  MQTT_RETAIN: bool
  HOSTIP: str
